theme: jekyll-theme-minimal
title: Geek Source
description: An online shopping experience providing a number of real-world challenges front-end developers face daily as professional developers.
logo: https://wesdollar.github.io/geek-source/assets/logo.png
markdown: GFM
